name: build
on:
  push:
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: get date for caching
        id: get-week-number
        run: echo "cachedate=$(/bin/date -u "+%U")" >>$GITHUB_OUTPUT
        shell: bash

      - name: cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-os-${{ runner.os }}-weeknum-${{ steps.get-week-number.outputs.cachedate }}-job-${{ github.job }}

      - run: python -m pip install tox

      - run: python -m tox run -e mypy

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py: ['3.7', '3.8', '3.9', '3.10', '3.11']
    name: "Run Tests on ${{ matrix.os }}, py${{ matrix.py }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: get date for caching
        id: get-week-number
        run: echo "cachedate=$(/bin/date -u "+%U")" >>$GITHUB_OUTPUT
        shell: bash

      - name: cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-os-${{ runner.os }}-weeknum-${{ steps.get-week-number.outputs.cachedate }}-job-${{ github.job }}

      - run: python -m pip install tox

      - name: cache tox virtualenvs
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-os-${{ runner.os }}-py${{ matrix.py }}-weeknum-${{ steps.get-week-number.outputs.cachedate }}-job-${{ github.job }}-hash-${{ hashFiles('tox.ini', 'setup.cfg') }}

      - name: test
        run: python -m tox run -m ci
      - name: twine-check
        run: python -m tox run -e twine-check

  self-check:
    name: "Self-Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: get date for caching
        id: get-week-number
        run: echo "cachedate=$(/bin/date -u "+%U")" >>$GITHUB_OUTPUT
        shell: bash

      - name: cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-os-${{ runner.os }}-weeknum-${{ steps.get-week-number.outputs.cachedate }}-job-${{ github.job }}

      - name: install from source
        run: |
          python -m pip install -U pip setuptools
          python -m pip install .

      - name: run on own workflows via HTTPS schema
        run: check-jsonschema  --schemafile "https://json.schemastore.org/github-workflow" .github/workflows/*.yaml

      - name: run on own workflows via vendored schema
        run: check-jsonschema  --builtin-schema vendor.github-workflows .github/workflows/*.yaml
